/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComoJogarRouteImport } from './routes/como-jogar'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RegrasRouteImport } from './routes/regras'
import { Route as SucessoRouteImport } from './routes/sucesso'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ApiPublicMercadopagoRouteImport } from './routes/api/public/mercadopago'
import { Route as ApiPublicPluginRouteImport } from './routes/api/public/plugin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoJogarRoute = ComoJogarRouteImport.update({
  id: '/como-jogar',
  path: '/como-jogar',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RegrasRoute = RegrasRouteImport.update({
  id: '/regras',
  path: '/regras',
  getParentRoute: () => rootRouteImport,
} as any)
const SucessoRoute = SucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoRoute = ApiPublicMercadopagoRouteImport.update({
  id: '/api/public/mercadopago',
  path: '/api/public/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPluginRoute = ApiPublicPluginRouteImport.update({
  id: '/api/public/plugin',
  path: '/api/public/plugin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/como-jogar': typeof ComoJogarRoute
  '/equipe': typeof EquipeRoute
  '/loja': typeof LojaRoute
  '/noticias': typeof NoticiasRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/regras': typeof RegrasRoute
  '/sucesso': typeof SucessoRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/api/public/mercadopago': typeof ApiPublicMercadopagoRoute
  '/api/public/plugin': typeof ApiPublicPluginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/como-jogar': typeof ComoJogarRoute
  '/equipe': typeof EquipeRoute
  '/loja': typeof LojaRoute
  '/noticias': typeof NoticiasRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/regras': typeof RegrasRoute
  '/sucesso': typeof SucessoRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/api/public/mercadopago': typeof ApiPublicMercadopagoRoute
  '/api/public/plugin': typeof ApiPublicPluginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/como-jogar': typeof ComoJogarRoute
  '/equipe': typeof EquipeRoute
  '/loja': typeof LojaRoute
  '/noticias': typeof NoticiasRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/regras': typeof RegrasRoute
  '/sucesso': typeof SucessoRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/api/public/mercadopago': typeof ApiPublicMercadopagoRoute
  '/api/public/plugin': typeof ApiPublicPluginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/como-jogar'
    | '/equipe'
    | '/loja'
    | '/noticias'
    | '/perfil'
    | '/privacidade'
    | '/ranking'
    | '/regras'
    | '/sucesso'
    | '/suporte'
    | '/termos'
    | '/api/public/mercadopago'
    | '/api/public/plugin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/como-jogar'
    | '/equipe'
    | '/loja'
    | '/noticias'
    | '/perfil'
    | '/privacidade'
    | '/ranking'
    | '/regras'
    | '/sucesso'
    | '/suporte'
    | '/termos'
    | '/api/public/mercadopago'
    | '/api/public/plugin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/como-jogar'
    | '/equipe'
    | '/loja'
    | '/noticias'
    | '/perfil'
    | '/privacidade'
    | '/ranking'
    | '/regras'
    | '/sucesso'
    | '/suporte'
    | '/termos'
    | '/api/public/mercadopago'
    | '/api/public/plugin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ComoJogarRoute: typeof ComoJogarRoute
  EquipeRoute: typeof EquipeRoute
  LojaRoute: typeof LojaRoute
  NoticiasRoute: typeof NoticiasRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RankingRoute: typeof RankingRoute
  RegrasRoute: typeof RegrasRoute
  SucessoRoute: typeof SucessoRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
  ApiPublicMercadopagoRoute: typeof ApiPublicMercadopagoRoute
  ApiPublicPluginRoute: typeof ApiPublicPluginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-jogar': {
      id: '/como-jogar'
      path: '/como-jogar'
      fullPath: '/como-jogar'
      preLoaderRoute: typeof ComoJogarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regras': {
      id: '/regras'
      path: '/regras'
      fullPath: '/regras'
      preLoaderRoute: typeof RegrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sucesso': {
      id: '/sucesso'
      path: '/sucesso'
      fullPath: '/sucesso'
      preLoaderRoute: typeof SucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago': {
      id: '/api/public/mercadopago'
      path: '/api/public/mercadopago'
      fullPath: '/api/public/mercadopago'
      preLoaderRoute: typeof ApiPublicMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plugin': {
      id: '/api/public/plugin'
      path: '/api/public/plugin'
      fullPath: '/api/public/plugin'
      preLoaderRoute: typeof ApiPublicPluginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ComoJogarRoute: ComoJogarRoute,
  EquipeRoute: EquipeRoute,
  LojaRoute: LojaRoute,
  NoticiasRoute: NoticiasRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RankingRoute: RankingRoute,
  RegrasRoute: RegrasRoute,
  SucessoRoute: SucessoRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
  ApiPublicMercadopagoRoute: ApiPublicMercadopagoRoute,
  ApiPublicPluginRoute: ApiPublicPluginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
