/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComoJogarRouteImport } from './routes/como-jogar'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RegrasRouteImport } from './routes/regras'
import { Route as SucessoRouteImport } from './routes/sucesso'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditoriaRouteImport } from './routes/admin/auditoria'
import { Route as AdminCategoriasRouteImport } from './routes/admin/categorias'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminCuponsRouteImport } from './routes/admin/cupons'
import { Route as AdminEntregasRouteImport } from './routes/admin/entregas'
import { Route as AdminJogadoresRouteImport } from './routes/admin/jogadores'
import { Route as AdminNoticiasRouteImport } from './routes/admin/noticias'
import { Route as AdminPagamentosRouteImport } from './routes/admin/pagamentos'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminProdutosRouteImport } from './routes/admin/produtos'
import { Route as AdminRankingRouteImport } from './routes/admin/ranking'
import { Route as AdminServidoresRouteImport } from './routes/admin/servidores'
import { Route as AdminTicketsRouteImport } from './routes/admin/tickets'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminCategoriasNewRouteImport } from './routes/admin/categorias/new'
import { Route as ApiPublicMercadopagoRouteImport } from './routes/api/public/mercadopago'
import { Route as ApiPublicPluginRouteImport } from './routes/api/public/plugin'
import { Route as AdminCategoriasCategoryIdEditRouteImport } from './routes/admin/categorias/$categoryId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoJogarRoute = ComoJogarRouteImport.update({
  id: '/como-jogar',
  path: '/como-jogar',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RegrasRoute = RegrasRouteImport.update({
  id: '/regras',
  path: '/regras',
  getParentRoute: () => rootRouteImport,
} as any)
const SucessoRoute = SucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntregasRoute = AdminEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJogadoresRoute = AdminJogadoresRouteImport.update({
  id: '/jogadores',
  path: '/jogadores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticiasRoute = AdminNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRankingRoute = AdminRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServidoresRoute = AdminServidoresRouteImport.update({
  id: '/servidores',
  path: '/servidores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasNewRoute = AdminCategoriasNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCategoriasRoute,
} as any)
const ApiPublicMercadopagoRoute = ApiPublicMercadopagoRouteImport.update({
  id: '/api/public/mercadopago',
  path: '/api/public/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPluginRoute = ApiPublicPluginRouteImport.update({
  id: '/api/public/plugin',
  path: '/api/public/plugin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriasCategoryIdEditRoute =
  AdminCategoriasCategoryIdEditRouteImport.update({
    id: '/$categoryId/edit',
    path: '/$categoryId/edit',
    getParentRoute: () => AdminCategoriasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/como-jogar': typeof ComoJogarRoute
  '/equipe': typeof EquipeRoute
  '/loja': typeof LojaRoute
  '/noticias': typeof NoticiasRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/regras': typeof RegrasRoute
  '/sucesso': typeof SucessoRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/categorias': typeof AdminCategoriasRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/entregas': typeof AdminEntregasRoute
  '/admin/jogadores': typeof AdminJogadoresRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/ranking': typeof AdminRankingRoute
  '/admin/servidores': typeof AdminServidoresRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/categorias/new': typeof AdminCategoriasNewRoute
  '/api/public/mercadopago': typeof ApiPublicMercadopagoRoute
  '/api/public/plugin': typeof ApiPublicPluginRoute
  '/admin/categorias/$categoryId/edit': typeof AdminCategoriasCategoryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-jogar': typeof ComoJogarRoute
  '/equipe': typeof EquipeRoute
  '/loja': typeof LojaRoute
  '/noticias': typeof NoticiasRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/regras': typeof RegrasRoute
  '/sucesso': typeof SucessoRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/categorias': typeof AdminCategoriasRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/entregas': typeof AdminEntregasRoute
  '/admin/jogadores': typeof AdminJogadoresRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/ranking': typeof AdminRankingRoute
  '/admin/servidores': typeof AdminServidoresRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin': typeof AdminIndexRoute
  '/admin/categorias/new': typeof AdminCategoriasNewRoute
  '/api/public/mercadopago': typeof ApiPublicMercadopagoRoute
  '/api/public/plugin': typeof ApiPublicPluginRoute
  '/admin/categorias/$categoryId/edit': typeof AdminCategoriasCategoryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/como-jogar': typeof ComoJogarRoute
  '/equipe': typeof EquipeRoute
  '/loja': typeof LojaRoute
  '/noticias': typeof NoticiasRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/regras': typeof RegrasRoute
  '/sucesso': typeof SucessoRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/categorias': typeof AdminCategoriasRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/entregas': typeof AdminEntregasRoute
  '/admin/jogadores': typeof AdminJogadoresRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/ranking': typeof AdminRankingRoute
  '/admin/servidores': typeof AdminServidoresRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/categorias/new': typeof AdminCategoriasNewRoute
  '/api/public/mercadopago': typeof ApiPublicMercadopagoRoute
  '/api/public/plugin': typeof ApiPublicPluginRoute
  '/admin/categorias/$categoryId/edit': typeof AdminCategoriasCategoryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/como-jogar'
    | '/equipe'
    | '/loja'
    | '/noticias'
    | '/perfil'
    | '/privacidade'
    | '/ranking'
    | '/regras'
    | '/sucesso'
    | '/suporte'
    | '/termos'
    | '/admin/auditoria'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/entregas'
    | '/admin/jogadores'
    | '/admin/noticias'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/ranking'
    | '/admin/servidores'
    | '/admin/tickets'
    | '/admin/usuarios'
    | '/admin/'
    | '/admin/categorias/new'
    | '/api/public/mercadopago'
    | '/api/public/plugin'
    | '/admin/categorias/$categoryId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/como-jogar'
    | '/equipe'
    | '/loja'
    | '/noticias'
    | '/perfil'
    | '/privacidade'
    | '/ranking'
    | '/regras'
    | '/sucesso'
    | '/suporte'
    | '/termos'
    | '/admin/auditoria'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/entregas'
    | '/admin/jogadores'
    | '/admin/noticias'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/ranking'
    | '/admin/servidores'
    | '/admin/tickets'
    | '/admin/usuarios'
    | '/admin'
    | '/admin/categorias/new'
    | '/api/public/mercadopago'
    | '/api/public/plugin'
    | '/admin/categorias/$categoryId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/como-jogar'
    | '/equipe'
    | '/loja'
    | '/noticias'
    | '/perfil'
    | '/privacidade'
    | '/ranking'
    | '/regras'
    | '/sucesso'
    | '/suporte'
    | '/termos'
    | '/admin/auditoria'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/entregas'
    | '/admin/jogadores'
    | '/admin/noticias'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/ranking'
    | '/admin/servidores'
    | '/admin/tickets'
    | '/admin/usuarios'
    | '/admin/'
    | '/admin/categorias/new'
    | '/api/public/mercadopago'
    | '/api/public/plugin'
    | '/admin/categorias/$categoryId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComoJogarRoute: typeof ComoJogarRoute
  EquipeRoute: typeof EquipeRoute
  LojaRoute: typeof LojaRoute
  NoticiasRoute: typeof NoticiasRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RankingRoute: typeof RankingRoute
  RegrasRoute: typeof RegrasRoute
  SucessoRoute: typeof SucessoRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
  ApiPublicMercadopagoRoute: typeof ApiPublicMercadopagoRoute
  ApiPublicPluginRoute: typeof ApiPublicPluginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-jogar': {
      id: '/como-jogar'
      path: '/como-jogar'
      fullPath: '/como-jogar'
      preLoaderRoute: typeof ComoJogarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regras': {
      id: '/regras'
      path: '/regras'
      fullPath: '/regras'
      preLoaderRoute: typeof RegrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sucesso': {
      id: '/sucesso'
      path: '/sucesso'
      fullPath: '/sucesso'
      preLoaderRoute: typeof SucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entregas': {
      id: '/admin/entregas'
      path: '/entregas'
      fullPath: '/admin/entregas'
      preLoaderRoute: typeof AdminEntregasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jogadores': {
      id: '/admin/jogadores'
      path: '/jogadores'
      fullPath: '/admin/jogadores'
      preLoaderRoute: typeof AdminJogadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/noticias': {
      id: '/admin/noticias'
      path: '/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AdminNoticiasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ranking': {
      id: '/admin/ranking'
      path: '/ranking'
      fullPath: '/admin/ranking'
      preLoaderRoute: typeof AdminRankingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servidores': {
      id: '/admin/servidores'
      path: '/servidores'
      fullPath: '/admin/servidores'
      preLoaderRoute: typeof AdminServidoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias/new': {
      id: '/admin/categorias/new'
      path: '/new'
      fullPath: '/admin/categorias/new'
      preLoaderRoute: typeof AdminCategoriasNewRouteImport
      parentRoute: typeof AdminCategoriasRoute
    }
    '/api/public/mercadopago': {
      id: '/api/public/mercadopago'
      path: '/api/public/mercadopago'
      fullPath: '/api/public/mercadopago'
      preLoaderRoute: typeof ApiPublicMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plugin': {
      id: '/api/public/plugin'
      path: '/api/public/plugin'
      fullPath: '/api/public/plugin'
      preLoaderRoute: typeof ApiPublicPluginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorias/$categoryId/edit': {
      id: '/admin/categorias/$categoryId/edit'
      path: '/$categoryId/edit'
      fullPath: '/admin/categorias/$categoryId/edit'
      preLoaderRoute: typeof AdminCategoriasCategoryIdEditRouteImport
      parentRoute: typeof AdminCategoriasRoute
    }
  }
}

interface AdminCategoriasRouteChildren {
  AdminCategoriasNewRoute: typeof AdminCategoriasNewRoute
  AdminCategoriasCategoryIdEditRoute: typeof AdminCategoriasCategoryIdEditRoute
}

const AdminCategoriasRouteChildren: AdminCategoriasRouteChildren = {
  AdminCategoriasNewRoute: AdminCategoriasNewRoute,
  AdminCategoriasCategoryIdEditRoute: AdminCategoriasCategoryIdEditRoute,
}

const AdminCategoriasRouteWithChildren = AdminCategoriasRoute._addFileChildren(
  AdminCategoriasRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminCategoriasRoute: typeof AdminCategoriasRouteWithChildren
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminEntregasRoute: typeof AdminEntregasRoute
  AdminJogadoresRoute: typeof AdminJogadoresRoute
  AdminNoticiasRoute: typeof AdminNoticiasRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminRankingRoute: typeof AdminRankingRoute
  AdminServidoresRoute: typeof AdminServidoresRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminCategoriasRoute: AdminCategoriasRouteWithChildren,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminEntregasRoute: AdminEntregasRoute,
  AdminJogadoresRoute: AdminJogadoresRoute,
  AdminNoticiasRoute: AdminNoticiasRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminRankingRoute: AdminRankingRoute,
  AdminServidoresRoute: AdminServidoresRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ComoJogarRoute: ComoJogarRoute,
  EquipeRoute: EquipeRoute,
  LojaRoute: LojaRoute,
  NoticiasRoute: NoticiasRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RankingRoute: RankingRoute,
  RegrasRoute: RegrasRoute,
  SucessoRoute: SucessoRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
  ApiPublicMercadopagoRoute: ApiPublicMercadopagoRoute,
  ApiPublicPluginRoute: ApiPublicPluginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
